#!/bin/bash

function supportedVersion() {
    (
        export MONGO_IMAGE_TAG=$1
        export MONGO_IMAGE_TAG_DNS=$(echo $1 | tr '.' '-')

        echo '---'
        cat mongo-tagged.yaml | envsubst
        echo '...'
    )
}

eval $(pelton variables ../..)

for image in $(echo "$SUPPORTED_MONGO_VERSIONS" | tr ',' '\n'); do
    supportedVersion $image
done
